## This file (digInFinancialMathematics.sage) was *autogenerated* from the file digInFinancialMathematics.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('digInFinancialMathematics')
_st_.endofdoc()
