## This file (digInHigherOrderDerivativesAndGraphs.sage) was *autogenerated* from the file digInHigherOrderDerivativesAndGraphs.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('digInHigherOrderDerivativesAndGraphs')
_st_.endofdoc()
