## This file (digInIdeaOfSubstitution.sage) was *autogenerated* from the file digInIdeaOfSubstitution.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('digInIdeaOfSubstitution')
_st_.endofdoc()
