## This file (digInFunctionsOfSeveralVariables.sage) was *autogenerated* from the file digInFunctionsOfSeveralVariables.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('digInFunctionsOfSeveralVariables')
